Import('env')
env = env.Clone()

env['CPPDEFINES'] += ['_USRDLL', 'DFSCACM_EXPORTS']

target = 'dfscacm'
env['PDB'] = target + '.pdb'
bin = env.SharedLibrary(
  target,
  [
    'codec.c',
    'dfscacm.def',
    env.RES('codec.rc')
  ]
)
env.Install('#/src/dist/bin', bin[0])
