Import('env')

env = env.Clone()

env['CPPDEFINES'] += ['_USRDLL']
env['CPPPATH'] = ['../sdks/Vegas/ffp', '..', '../fscommon', '../dfsc', '../utils']
env['LIBS'] += ['rpcrt4.lib', 'wininet.lib']

target = 'dfscVegasOut'
env['PDB'] = target + '.pdb'
bin = env.SharedLibrary(
  target,
  [
    'VegasFSMain.cpp',
    'VegasFS.cpp',
    'VegasFSRender.cpp',
    '../sdks/Vegas/ffp/SfHelpers.cpp',
    'VegasFS.def',
    env.RES('VegasFS.rc'),
  ]
)
env.Install('#/src/dist/bin', bin[0])
