Import('env')

env = env.Clone()

env['CPPDEFINES'] += ['_USRDLL']
env['RCFLAGS'] += ['/d', 'PRWIN_ENV']
env['CPPPATH'] = ['../sdks/Premiere/cs5/examples/headers', '..', '../fscommon', '../dfsc', '../utils']
env['LIBS'].remove('common.lib')
env['LIBS'] += ['dokan1.lib', 'rpcrt4.lib', 'wininet.lib', 'common.lib']
env['LIBPATH'] += ['../dokanserve/dokan/lib']

env['PDB'] = 'dfscPremiereOut.pdb'
bin = env.SharedLibrary(
  'dfscPremiereOut',
  [
    'PremiereFS.cpp',
  ],
  SHLIBSUFFIX = '.prm'
)

# Add a post-build step to embed the manifest using mt.exe
# The number at the end of the line indicates the file type (1: EXE; 2:DLL).
if not env['dbg']:
  env.AddPostAction(bin,
    'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')
env.Install('#/src/dist/bin', bin[0])
