Import('env')
Import('env_vc9_x64')

env = env.Clone()

env['CPPDEFINES'] += ['_USRDLL']

target = 'dfsc'
env['PDB'] = target + '.pdb'
bin = env.SharedLibrary(
  target,
  [
    'dfsc.cpp',
    'dfsc.def',
  ]
)
env.Install('#/src/dist/bin', bin[0])

env64 = env_vc9_x64.Clone()
env64['CPPDEFINES'] += ['_USRDLL']

target64 = 'dfsc64'
env64['PDB'] = target64 + '.pdb'
bin = env64.SharedLibrary(
  target64,
  [
    'dfsc.cpp',
    'dfsc.def',
  ]
)
env64.Install('#/src/dist/bin', bin[0])
