Import('env')
env = env.Clone()

env['CPPDEFINES'] += ['_USRDLL']

target = 'dfsc'
env['PDB'] = target + '.pdb'
bin = env.SharedLibrary(
  target,
  [
    'dfsc.cpp',
    'dfsc.def',
  ]
)
env.Install('#/src/dist/bin', bin[0])
