Import('env')

env = env.Clone()

env['CPPDEFINES'] += ['_USRDLL']
env['CPPPATH'] = ['../sdks/Wax', '..', '../fscommon', '../dfsc', '../utils']
env['LIBS'] += ['rpcrt4.lib', 'wininet.lib']

target = 'dfscWaxOut'
env['PDB'] = target + '.pdb'
bin = env.SharedLibrary(
  target,
  [
    'WaxFS.cpp',
    'WaxFS.def',
  ]
)
env.Install('#/src/dist/bin', bin[0])
