Import('env')

env.SConscript(
  [
    'dfsc/SConscript',
    'fscommon/SConscript',
    'NetClient/SConscript',
    'NetServer/SConscript',
    'PremiereV2/SConscript',
    'VegasV2/SConscript',
#    'Wax/SConscript',
    'dist/SConscript',
    'dokanserve/SConscript',
  ]
)
